{% set name = "FreeFem" %}
{% set version = "4.13" %}
{% set build = 17 %}

# ensure mpi is defined (needed for conda-smithy recipe-lint)
{% set mpi = mpi or 'nompi' %}

{% if mpi == 'nompi' %}
# prioritize nompi variant via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}-sources/archive/refs/tags/v{{ version }}.tar.gz
  sha256: aefd4ff02333209f7433abef2e74acb621b6946063ff27e81cf2da43120b6ae4
  patches:
    - Makefile.am_conda.patch
    - Makefile.am_src_bin-win32_conda.patch

build:
  number: {{ build }}
  skip: true  # [osx or win or py2ks]
  # Per https://conda-forge.org/docs/maintainer/knowledge_base.html#preferring-a-provider-usually-nompi
  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `pkg * mpi_mpich_*` for mpich
  # `pkg * mpi_*` for any mpi
  # `pkg * nompi_*` for no mpi

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"
  run_exports:
    - {{ pin_subpackage('freefem', max_pin='x.x') }} {{ mpi_prefix }}_*  

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ stdlib("c") }}    # [unix]
    - {{ compiler('cxx') }}  # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("c") }}          # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]    
    - autoconf  # [unix]
    - m2-autoconf  # [win]
    - m2-automake-wrapper  # [win]
    - automake  # [unix]
    - bison  # [unix]
    - m2-bison  # [win]
    - flex  # [unix]
    - m2-flex  # [win]
    - m4  # [unix]
    - m2-m4  # [win]
    - make  # [unix]
    - m2w64-make  # [win]    
    - patch  # [unix]
    - m2-patch  # [win]
    - m2-base  # [win]    
    - unzip  # [unix]
    - m2-unzip  # [win]
  host:
    - arpack
    - fftw
    - gmm  # [unix]
    - gsl
    - freeglut  # [linux]
    - ipopt
    - nlopt
    - metis
    - mumps-seq  # [not osx and mpi == 'nompi']
    - mumps-mpi  # [mpi != 'nompi']
    - petsc  # [not osx]
    - slepc  # [unix]
    - parmetis
    - mmgsuite
    - scalapack
    - scotch
    - hdf5
    - lapack
    - openblas
    - suitesparse
    - superlu  # [unix]
    - tetgen
    - zlib
    - zstd
    - {{ mpi }}  # [mpi != 'nompi']
  run:
    - {{ mpi }}  # [mpi != 'nompi']
    - {{ pin_compatible('hdf5', max_pin='x.x') }}
    - {{ pin_compatible('lapack', max_pin='x.x') }}

test:
  commands:
    - test -f $PREFIX/bin/FreeFem++  # [unix]
    - if not exist $PREFIX\\bin\\FreeFem++ exit 1  # [win]    
    - test -f $PREFIX/bin/FreeFem++-nw  # [unix]
    - if not exist $PREFIX\\bin\\FreeFem++-nw exit 1  # [win] 
    - test -f $PREFIX/bin/ff-c++  # [unix]
    - if not exist $PREFIX\\bin\\ff-c++ exit 1  # [win] 
    - test -f $PREFIX/bin/ff-get-dep  # [unix]
    - if not exist $PREFIX\\bin\\ff-get-dep exit 1  # [win]
    - test -f $PREFIX/bin/ff-pkg-download  # [unix
    - if not exist $PREFIX\\bin\\ff-pkg-download exit 1  # [win]
    - FreeFem++ $PREFIX/share/FreeFEM/${PKG_VERSION}/examples/tutorial/beam.edp  # [linux]
    - FreeFem++ $PREFIX/share/FreeFEM/${PKG_VERSION}/examples/3dSurf/buildMeshSfromMesh3.edp  # [linux]

about:
  home: https://freefem.org/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: 'FreeFem : A high level multiphysics finite element software'
  description: >
    FreeFEM is a popular 2D and 3D partial differential equations (PDE) solver used by thousands of researchers across the world. It allows you to easily implement your own physics modules using the provided FreeFEM language. FreeFEM offers a large list of finite elements, like the Lagrange, Taylor-Hood, etc., usable in
    the continuous and discontinuous Galerkin method framework.
  doc_url: https://doc.freefem.org
  dev_url: https://github.com/FreeFem

extra:
  recipe-maintainers:
    - ldallolio
    - cnrdn
    - fbordeu
